services:

  igloo-server:
    build          : ./
    env_file       : .env
    image          : igloo-server:latest
    container_name : igloo-server
    platform       : linux/x86_64
    hostname       : igloo-server
    restart        : unless-stopped
    init           : true
    tty            : true
    networks:
      - infranet
    ports:
      - "8002:8002"
    volumes:
      - ./src:/app/src:rw

networks:
  infranet:
    driver: bridge
