services:

  igloo-server:
    build          : ./
    env_file       : .env
    image          : igloo-server
    environment:
      - HOST_NAME=0.0.0.0
      - HOST_PORT=8002
      - NODE_ENV=production
      # Explicit DB path inside the container; lives under /app/data
      - DB_PATH=/app/data/igloo.db
    container_name : igloo-server
    platform       : linux/x86_64
    hostname       : igloo-server
    restart        : unless-stopped
    init           : true
    tty            : true
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8002/api/status || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - infranet
    ports:
      - "8002:8002"
    volumes:
      - ./src:/app/src:rw
      # Persist database and session secrets between container recreations
      - ./data:/app/data:rw

networks:
  infranet:
    driver: bridge
